# Generated by Django 5.0.3 on 2025-09-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_category_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prodect',
        ),
    ]
