# Generated by Django 5.0.3 on 2025-09-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
